---
title: "stats 2"
author: "Shawn Vizgan"
date: "9/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



question 1 
```{r}
"scores" <- c(2,3,4,5,6,7,8,9,10,46)

mean(scores)


min(scores)
max(scores)

numbers_to_test <- min(scores):max(scores)

sum_deviations <-c() 
  for(i in numbers_to_test) {
  sum_deviations[i] <- sum(scores-i)
}

sum_deviations

plot(abs(sum_deviations))

which(sum_deviations == 0)
```

question 2
```{r}
y <- c(2,4,6,8,10,13,16,19,22,26)


sum(y)
mean(y)/length(y)

sum((y-mean(y))^2)/(length(y)-1)

var(y)

             
             
             
             
             
        



```

question 3
```{r}
library(dplyr)

library(ggplot2)


class <- c('morning','afternoon','nighttime')
class_means <- c(85,90,93)

school_data <- data.frame(class, class_means)

str(school_data)


school_data$class <- factor(school_data$class, 
                            levels = c("morning","afternoon","nighttime"))



plot(school_data)             

ggplot(school_data, aes(x = class, y = class_means))+
  geom_bar(stat="identity")


```  






question 4
```{r}
library(dplyr)

library(ggplot2)


time_of_day <- c("morning","afternoon","nighttime")
 scores <- c(75,78,80,88,76,63)
instructor <- factor(c(1,1,1,2,2,2))
school_data <- data.frame(time_of_day, scores, instructor)

school_data$time_of_day <- factor(school_data$time_of_day, 
                            levels = c("morning","afternoon","nighttime"))

group_means <- school_data 
             
knitr::kable(group_means)                
                
             

ggplot(group_means, aes(x = time_of_day, y = scores , group = instructor, fill = instructor))+
  geom_bar(stat="identity" , position = "dodge" )

ggplot(group_means, aes(x = time_of_day, y = scores , fill = instructor))+
  geom_bar(stat="identity" , position = "dodge" ) + 
  facet_wrap(~instructor)


```


question 5
```{r}
whr2018_data <- read.table("open_data/WHR2018.csv",
                             sep = ",",
                             header = TRUE )



whr2018_data %>%
  filter( year >= 2010,
          year <= 2015) %>%
  group_by(year) %>%  
  summarize(mean_hleab = mean(Healthy.life.expectancy.at.birth, na.rm = TRUE))
           
```
question 6
```{r}
whr2018_data <- read.table("open_data/WHR2018.csv",
                             sep = ",",
                             header = TRUE )



whr2018_data %>%
  filter( year >= 2010,
          year <= 2015) %>%
  group_by(year) %>%  
  summarize(mean_hleab = mean(Healthy.life.expectancy.at.birth, na.rm = TRUE),
            sd_hleab = sd(Healthy.life.expectancy.at.birth, na.rm = TRUE))
```


